# Generated by Django 3.0.3 on 2020-11-08 04:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Kakeibo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(
                    default=datetime.datetime.now, verbose_name='Date')),
                ('money', models.IntegerField(
                    help_text='Australia dollars', verbose_name='Fee')),
                ('memo', models.CharField(max_length=500, verbose_name='Memo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                               to='kakeibo.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Kakeibo',
                'verbose_name_plural': 'Kakeibo',
                'db_table': 'kakeibo',
            },
        ),
    ]
