# Generated by Django 3.0.3 on 2020-11-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakeibo', '0002_auto_20190307_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_goal', models.IntegerField(help_text='Setting goal per week', verbose_name='weeklyGoal')),
                ('mothly_goal', models.IntegerField(help_text='Setting goal per month', verbose_name='monthlyGoal')),
                ('memo', models.CharField(max_length=400, verbose_name='Memo')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goal',
                'db_table': 'goal',
            },
        ),
    ]
